### ISSUE TITLE
Cannot view the (sub)workflow details if the metadata is too long

### ISSUE THREAD

**Issue by rexwangcc** [DataBiosphere/job-manager#574]
Sometimes when the workflow has too many shards, the content of its metadata will get too long/large, and the link to the workflows in Job Manager cannot work. Example: https://job-manager.caas-prod.broadinstitute.org/jobs/b429ebd9-c2be-4d7a-acef-adb9defa8897 if you click the `analysis` subworkflow, with `inpect` on Chrome, you will see 500 error occurred.

**Comment by ruchim** [comment]
One thing that JM can do is request specific bits of metadata from Cromwell to lessen the data being returned.

@cjllanwarne @rsasch @aednichols Might be good to sit down and tech talk how we can help JM do that when making requests to Cromwell (but not dsub)

**Comment by rexwangcc** [comment]
@ruchim That is a good way to go! I personally ended up using `includeKey ` and `excludeKey ` to query long metadata at the end. This will also potentially help the JMUI to scale better  🤔

**Comment by rsasch** [comment]
FYI, this was the output from the JM shim layer when I tried to view the `analysis` details:

``` cromwell_1         | ERROR:flask.app:Exception on /api/v1/jobs/1d5121a9-7c82-42be-acdd-cf3cbb3f2a66 [GET]
cromwell_1         | Traceback (most recent call last):
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
cromwell_1         |     response = self.full_dispatch_request()
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
cromwell_1         |     rv = self.handle_user_exception(e)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
cromwell_1         |     reraise(exc_type, exc_value, tb)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
cromwell_1         |     rv = self.dispatch_request()
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
cromwell_1         |     return self.view_functions[rule.endpoint](**req.view_args)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/decorator.py", line 66, in wrapper
cromwell_1         |     response = function(request)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/validation.py", line 293, in wrapper
cromwell_1         |     return function(request)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/decorator.py", line 42, in wrapper
cromwell_1         |     response = function(request)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 195, in wrapper
cromwell_1         |     return function(**kwargs)
cromwell_1         |   File "/home/vmagent/app/jobs/controllers/utils/auth.py", line 14, in wrapper
cromwell_1         |     return fn(*args, **kwargs)
cromwell_1         |   File "/home/vmagent/app/jobs/controllers/jobs_controller.py", line 94, in get_job
cromwell_1         |     url, auth=kwargs.get('auth'), headers=kwargs.get('auth_headers'))
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
cromwell_1         |     return request('get', url, params=params, **kwargs)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
cromwell_1         |     return session.request(method=method, url=url, **kwargs)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
cromwell_1         |     resp = self.send(prep, **send_kwargs)
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 677, in send
cromwell_1         |     r.content
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 828, in content
cromwell_1         |     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
cromwell_1         |   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 753, in generate
cromwell_1         |     raise ChunkedEncodingError(e)
cromwell_1         | ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by rexwangcc** [comment]
@rsasch FYI, I ran into the same error when trying to send requests directly to the CromIAM. It turned out to be an issue with the CromIAM side.

Slack discussions and workaround: https://broadinstitute.slack.com/archives/C1EH66VCM/p1551830049174300?thread_ts=1551811819.153700&cid=C1EH66VCM
Related issue: https://github.com/broadinstitute/cromwell/issues/4708
