### ISSUE TITLE
Missing name and error details when there's an input type error

### ISSUE THREAD

**Issue by breilly2** [DataBiosphere/job-manager#588]
I submitted a job (https://job-manager.dsde-prod.broadinstitute.org/jobs/62d69037-b6a8-4d45-bdd0-df6aa8dda668?q=submission-id%3D87c83516-5b93-4e9f-9318-5a094f5a5d07) that shows no error details even though the job failed. On the list page, there's nothing in the name column. On the detail page, there's no indication of the cause of the error.

Here's the error I found by drilling down in FireCloud:

> Failed to evaluate input 'do_the_thing.status' (reason 1 of 1): No coercion defined from '0' of type 'spray.json.JsNumber' to 'String'.

**Comment by aednichols** [comment]
Navigating to that URL on my machine crashes Job Manager, probably because I don't have permission. Job Manager in general is up though.

This may well be addressed already in https://github.com/DataBiosphere/job-manager/pull/587 which is merged but not released in the monolith.

![Screen Shot 2019-03-13 at 10 55 03 AM](https://user-images.githubusercontent.com/1087943/54288823-7c975880-457e-11e9-9710-51b0c71b1497.png)

**Comment by breilly2** [comment]
@aednichols I shared the workspace with you. Would it be helpful if I also share it with the FC support group?

**Comment by aednichols** [comment]
Still crashing, even though I should have permission - huh.

I'll investigate.

**Comment by aednichols** [comment]
Error is
```
ERROR:flask.app:Exception on /api/v1/jobs/62d69037-b6a8-4d45-bdd0-df6aa8dda668 [GET]
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
   rv = self.dispatch_request()
 File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/decorator.py", line 66, in wrapper
   response = function(request)
 File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/validation.py", line 293, in wrapper
   return function(request)
 File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/decorator.py", line 42, in wrapper
   response = function(request)
 File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 195, in wrapper
   return function(**kwargs)
 File "/home/vmagent/app/jobs/controllers/utils/auth.py", line 14, in wrapper
   return fn(*args, **kwargs)
 File "/home/vmagent/app/jobs/controllers/jobs_controller.py", line 100, in get_job
   job = response.json()
 File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
   return complexjson.loads(self.text, **kwargs)
 File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
   return _default_decoder.decode(s)
 File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
   raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by aednichols** [comment]
Ah, Job Manager was still using my fake email; when I switched to the real email that Brian shared with, it showed up fine.

The original bug still stands.

**Comment by rsasch** [comment]
Cromwell doesn't return the name of the workflow when it fails validation, so Job Manager is not able to display that.  Job Manager should be able to display the error messages that Cromwell does return, so that is a bug.
